query Donation($id: ID! $self: String){
    donation(id: $id) {
	id
	description 
	amount
	created
	likeCount
	user {
	    id
	    username
	    name
	    avatar
	    person {
		id
	    }
	}
	target {
	    id
	    title
	    category {
		id
	    }
	}
	hasLiked: like(id: $self) {
	    edges {
		node {
		    id
		}
	    }
	}
	entryPtr {
	    id
	    commentCountRecursive
	}
    }
}
