query News($id: ID! $self: String){
    news(id: $id){
	id
	title
	created
	description
	image
	user {
	    id
	    name
	    avatar
	    nonprofit {
		id
		title
		category {
		    id
		}
	    }
	}
	hasLiked: like(id: $self) {
	    edges {
		node {
		    id
		}
	    }
	}
	hasBookmarked: bookmark(id: $self) {
	    edges {
		node {
		    id
		}
	    }
	}
    }
}
