query NewsList($self: String $search: String $byUser: String $byFollowing: String $bookmarkBy: String $orderBy: String $first: Int $after: String) {
    allNews(search: $search byUser: $byUser byFollowing: $byFollowing bookmarkBy: $bookmarkBy orderBy: $orderBy first: $first after: $after) {
	edges {
  	    node {
		id
		title
		image
		description
		created
		user {
		    id
		    name
		    avatar
		    nonprofit {
			id
			category {
			    id
			}
		    }
		}
		hasLiked: like(id: $self) {
		    edges {
			node {
			    id
			}
		    }
		}
		hasBookmarked: bookmark(id: $self) {
		    edges {
			node {
			    id
			}
		    }
		}
	    }
	    cursor
	}
	pageInfo {
	    hasNextPage
	}
    }
}
