query Nonprofit($id: ID! $self: String){
    nonprofit(id: $id){
	id
	followerCount
	description
	title
	link
	avatar
	isFollowing: follower(id: $self) {
	    edges {
		node {
		    id
		}
	    }
	}
    }
}
