query NonprofitList($self: String $search: String $followedBy: String $orderBy: String $first: Int $after: String) {
    allNonprofits(search: $search followedBy: $followedBy orderBy: $orderBy first: $first after: $after) {
	edges {
  	    node {
		id
		username
		id
		title
		avatar
  		description
		category {
		    id
		}
		isFollowing: follower(id: $self) {
		    edges {
			node {
			    id
			}
		    }
		}
  	    }
	    cursor
	}
	pageInfo {
	    hasNextPage
	}
    }
}
