query Post($id: ID! $self: String){
    post(id: $id){
	id
	title
	created
	description
	user {
	    id
	    name
	    avatar
	    person {
		id
		name
	    }
	}
	hasLiked: like(id: $self) {
	    edges {
		node {
		    id
		}
	    }
	}
	hasBookmarked: bookmark(id: $self) {
	    edges {
		node {
		    id
		}
	    }
	}
    }
}
