query CommentTree($hasParent: String! $self: String) {
    allComments(hasParent: $hasParent orderBy: "-created") {
	edges {
	    node {
		id
		description
		created
		user {
		    id
		    name
		    username
		    avatar
		    person {
			id
		    }
		}
		hasLiked: like(id: $self) {
		    edges {
			node {
			    id
			}
		    }
		}
		entryPtr {
		    id
		    commentCount
		}
	    }
	}
    }
}
