query DonationList($self: String $search: String $byUser: String $byFollowing: String $orderBy: String $first: Int $after: String) {
    allDonations(search: $search byUser: $byUser byFollowing: $byFollowing orderBy: $orderBy first: $first after: $after) {
	edges {
  	    node {
		id
		amount
		description
		created
		likeCount
		target {
		    id
		    title
		    category {
			id
		    }
		}
		user {
		    id
		    name
		    avatar
		    person {
			id
		    }
		}
		hasLiked: like(id: $self) {
		    edges {
			node {
			    id
			}
		    }
		}
		entryPtr {
		    id
		    commentCountRecursive
		}
	    }
	    cursor
	}
	pageInfo {
	    hasNextPage
	}
    }
}
