query EventList($self: String $search: String $byUser: String $byFollowing: String $rsvpBy: String $beginDate: String $orderBy: String $first: Int $after: String) {
    allEvents(search: $search byUser: $byUser byFollowing: $byFollowing rsvpBy: $rsvpBy beginDate: $beginDate orderBy: $orderBy first: $first after: $after) {
	edges {
  	    node {
		id
  		title
		image
  		description
  		created
		date
		user {
		    id
		    name
		    avatar
		    nonprofit {
			id
			category {
			    id
			}
		    }
		}
		hasLiked: like(id: $self) {
		    edges {
			node {
			    id
			}
		    }
		}
		hasRsvp: rsvp(id: $self) {
		    edges {
			node {
			    id
			}
		    }
		}
	    }
	    cursor
	}
	pageInfo {
	    hasNextPage
	}
    }
}
