query PersonList($self: String $search: String $followedBy: String $followerOf: String $orderBy: String $first: Int $after: String) {
    allPeople(search: $search followedBy: $followedBy followerOf: $followerOf orderBy: $orderBy first: $first after: $after) {
	edges {
  	    node {
		id
		name
		username
		avatar
		balance
		followerCount
		followingCount
		dateJoined
		isFollowing: follower(id: $self) {
		    edges {
			node {
			    id
			}
		    }
		}
  	    }
	    cursor
	}
	pageInfo {
	    hasNextPage
	}
    }
}
