mutation TransactionCreate($user: ID! $target: ID! $amount: Int! $description: String!) {
    createTransaction(user: $user target: $target amount: $amount description: $description) {
	transaction {
	    id
	}
    }
}
